### ISSUE TITLE
Mac打包失败

### ISSUE THREAD

**Issue by koxiong** [TangSengDaoDao/TangSengDaoDaoWeb#47]
Node版本：v18.17.1
yarn版本：1.22.22
TangSengDaoDaoWeb的版本：今日clone的最新版本
kk@kkdeMacBook-Pro TangSengDaoDaoWeb % yarn run build
yarn run v1.22.22
$ turbo run build
╭──────────────────────────────────────────────────────────────────────────╮
│                                                                          │
│                     Update available v2.2.1 ≫ v2.3.3                     │
│    Changelog: https://github.com/vercel/turborepo/releases/tag/v2.3.3    │
│             Run "npx @turbo/codemod@latest update" to update             │
│                                                                          │
│          Follow @turborepo for updates: https://x.com/turborepo          │
╰──────────────────────────────────────────────────────────────────────────╯
turbo 2.2.1

• Packages in scope: @tsdaodao/base, @tsdaodao/contacts, @tsdaodao/datasource, @tsdaodao/login, @tsdaodao/web, eslint-config-custom, tsconfig
• Running build in 7 packages
• Remote caching disabled
@tsdaodao/web:build: cache hit (outputs already on disk), replaying logs 9231dc69defbde00
@tsdaodao/web:build: 
yarn run v1.22.22
$ cross-env REACT_APP_VERSION=$npm_package_version react-app-rewired build
@tsdaodao/web:build: Creating an optimized production build...
@tsdaodao/web:build: =============
@tsdaodao/web:build: 
@tsdaodao/web:build: WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
@tsdaodao/web:build: 
@tsdaodao/web:build: You may find that it works just fine, or you may not.
@tsdaodao/web:build: 
@tsdaodao/web:build: SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.2.0
@tsdaodao/web:build: 
@tsdaodao/web:build: YOUR TYPESCRIPT VERSION: 5.6.3
@tsdaodao/web:build: 
@tsdaodao/web:build: Please only submit bug reports when using the officially supported version.
@tsdaodao/web:build: 
@tsdaodao/web:build: =============
@tsdaodao/web:build: Compiled successfully.
@tsdaodao/web:build: 
@tsdaodao/web:build: File sizes after gzip:
@tsdaodao/web:build: 
@tsdaodao/web:build:   823.53 kB  build/static/js/main.eb3be439.js
@tsdaodao/web:build:   81.77 kB   build/static/css/main.4deb35cc.css
@tsdaodao/web:build:   1.74 kB    build/static/js/400.f4e57e17.chunk.js
@tsdaodao/web:build: 
@tsdaodao/web:build: The bundle size is significantly larger than recommended.
@tsdaodao/web:build: Consider reducing it with code splitting: https://goo.gl/9VhYWB
@tsdaodao/web:build: You can also analyze the project dependencies: https://goo.gl/LeUzfb
@tsdaodao/web:build: 
@tsdaodao/web:build: The project was built assuming it is hosted at ./.
@tsdaodao/web:build: You can control this with the homepage field in your package.json.
@tsdaodao/web:build: 
@tsdaodao/web:build: The build folder is ready to be deployed.
@tsdaodao/web:build: 
@tsdaodao/web:build: Find out more about deployment here:
@tsdaodao/web:build: 
@tsdaodao/web:build:   https://cra.link/deployment
@tsdaodao/web:build: 
✨  Done in 19.61s.

 Tasks:    1 successful, 1 total
Cached:    1 cached, 1 total
  Time:    168ms >>> FULL TURBO

✨  Done in 1.31s.
kk@kkMacBook-Pro TangSengDaoDaoWeb % yarn run build-ele:mac
yarn run v1.22.22
$ turbo run build && turbo run build-ele:mac
╭──────────────────────────────────────────────────────────────────────────╮
│                                                                          │
│                     Update available v2.2.1 ≫ v2.3.3                     │
│    Changelog: https://github.com/vercel/turborepo/releases/tag/v2.3.3    │
│             Run "npx @turbo/codemod@latest update" to update             │
│                                                                          │
│          Follow @turborepo for updates: https://x.com/turborepo          │
╰──────────────────────────────────────────────────────────────────────────╯
turbo 2.2.1

• Packages in scope: @tsdaodao/base, @tsdaodao/contacts, @tsdaodao/datasource, @tsdaodao/login, @tsdaodao/web, eslint-config-custom, tsconfig
• Running build in 7 packages
• Remote caching disabled
@tsdaodao/web:build: cache hit (outputs already on disk), replaying logs 9231dc69defbde00
@tsdaodao/web:build: 
yarn run v1.22.22
$ cross-env REACT_APP_VERSION=$npm_package_version react-app-rewired build
@tsdaodao/web:build: Creating an optimized production build...
@tsdaodao/web:build: =============
@tsdaodao/web:build: 
@tsdaodao/web:build: WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
@tsdaodao/web:build: 
@tsdaodao/web:build: You may find that it works just fine, or you may not.
@tsdaodao/web:build: 
@tsdaodao/web:build: SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.2.0
@tsdaodao/web:build: 
@tsdaodao/web:build: YOUR TYPESCRIPT VERSION: 5.6.3
@tsdaodao/web:build: 
@tsdaodao/web:build: Please only submit bug reports when using the officially supported version.
@tsdaodao/web:build: 
@tsdaodao/web:build: =============
@tsdaodao/web:build: Compiled successfully.
@tsdaodao/web:build: 
@tsdaodao/web:build: File sizes after gzip:
@tsdaodao/web:build: 
@tsdaodao/web:build:   823.53 kB  build/static/js/main.eb3be439.js
@tsdaodao/web:build:   81.77 kB   build/static/css/main.4deb35cc.css
@tsdaodao/web:build:   1.74 kB    build/static/js/400.f4e57e17.chunk.js
@tsdaodao/web:build: 
@tsdaodao/web:build: The bundle size is significantly larger than recommended.
@tsdaodao/web:build: Consider reducing it with code splitting: https://goo.gl/9VhYWB
@tsdaodao/web:build: You can also analyze the project dependencies: https://goo.gl/LeUzfb
@tsdaodao/web:build: 
@tsdaodao/web:build: The project was built assuming it is hosted at ./.
@tsdaodao/web:build: You can control this with the homepage field in your package.json.
@tsdaodao/web:build: 
@tsdaodao/web:build: The build folder is ready to be deployed.
@tsdaodao/web:build: 
@tsdaodao/web:build: Find out more about deployment here:
@tsdaodao/web:build: 
@tsdaodao/web:build:   https://cra.link/deployment
@tsdaodao/web:build: 
✨  Done in 19.61s.

 Tasks:    1 successful, 1 total
Cached:    1 cached, 1 total
  Time:    163ms >>> FULL TURBO

╭──────────────────────────────────────────────────────────────────────────╮
│                                                                          │
│                     Update available v2.2.1 ≫ v2.3.3                     │
│    Changelog: https://github.com/vercel/turborepo/releases/tag/v2.3.3    │
│             Run "npx @turbo/codemod@latest update" to update             │
│                                                                          │
│          Follow @turborepo for updates: https://x.com/turborepo          │
╰──────────────────────────────────────────────────────────────────────────╯
turbo 2.2.1

• Packages in scope: @tsdaodao/base, @tsdaodao/contacts, @tsdaodao/datasource, @tsdaodao/login, @tsdaodao/web, eslint-config-custom, tsconfig
• Running build-ele:mac in 7 packages
• Remote caching disabled
@tsdaodao/web:build-ele:mac: cache miss, executing ec0f860455de1fa4
@tsdaodao/web:build-ele:mac: 
yarn run v1.22.22
$ tsc -p tsconfig.e.json && electron-builder --mac -c
@tsdaodao/web:build-ele:mac: 
@tsdaodao/web:build-ele:mac: /private/tmp/TangSengDaoDaoWeb/node_modules/cliui/build/index.cjs:293
@tsdaodao/web:build-ele:mac: const wrap = require('wrap-ansi');
@tsdaodao/web:build-ele:mac:              ^
@tsdaodao/web:build-ele:mac: Error [ERR_REQUIRE_ESM]: require() of ES Module /private/tmp/TangSengDaoDaoWeb/node_modules/wrap-ansi/index.js from /private/tmp/TangSengDaoDaoWeb/node_modules/cliui/build/index.cjs not supported.
@tsdaodao/web:build-ele:mac: Instead change the require of index.js in /private/tmp/TangSengDaoDaoWeb/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
@tsdaodao/web:build-ele:mac:     at Object.<anonymous> (/private/tmp/TangSengDaoDaoWeb/node_modules/cliui/build/index.cjs:293:14)
@tsdaodao/web:build-ele:mac:     at Object.<anonymous> (/private/tmp/TangSengDaoDaoWeb/node_modules/yargs/build/index.cjs:1:60678)
@tsdaodao/web:build-ele:mac:     at Object.<anonymous> (/private/tmp/TangSengDaoDaoWeb/node_modules/yargs/index.cjs:5:30)
@tsdaodao/web:build-ele:mac:     at Object.<anonymous> (/private/tmp/TangSengDaoDaoWeb/node_modules/electron-builder/out/builder.js:7:15)
@tsdaodao/web:build-ele:mac:     at Object.<anonymous> (/private/tmp/TangSengDaoDaoWeb/node_modules/electron-builder/out/cli/cli.js:11:19)
@tsdaodao/web:build-ele:mac:     at Object.<anonymous> (/private/tmp/TangSengDaoDaoWeb/node_modules/electron-builder/cli.js:4:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@tsdaodao/web:build-ele:mac: ERROR: command finished with error: command (/private/tmp/TangSengDaoDaoWeb/apps/web) /var/folders/wb/3qg388_n1gn31tzwp77qhn9c0000gn/T/yarn--1734878874006-0.9477602106827858/yarn run build-ele:mac exited (1)
@tsdaodao/web#build-ele:mac: command (/private/tmp/TangSengDaoDaoWeb/apps/web) /var/folders/wb/3qg388_n1gn31tzwp77qhn9c0000gn/T/yarn--1734878874006-0.9477602106827858/yarn run build-ele:mac exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    1.119s 
Failed:    @tsdaodao/web#build-ele:mac

 ERROR  run failed: command  exited (1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by tangtaoit** [comment]
node v22.12.0、 yarn 1.22.19 使用这两个版本构建
